### ISSUE TITLE
If clang 7 is used, clang-format disagrees with formatting in master

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#1038]
# Environment

* OS version: Linux
* Elona foobar verision: 47a8729dad5db35ba2bb5364f43294888f684138

# Details
Since 47a8729dad5db35ba2bb5364f43294888f684138, the `clang-format` provided in `clang 7` will produce different indentation than that of a fresh copy of `develop`. This causes CI to fail if `make format` is re-run using this version of `clang-format`. To me it isn't really clear what version of `clang-format` was used to format `master`, and the version I use is the  one from the official `clang` package in Arch Linux. It may cause difficulty if contributions are submitted where `clang 7` was installed at the time.

**Comment by ki-foobar** [comment]
The result of `clang-format --version` in my environment.
```
$ clang-format --version
clang-format version 8.0.0 (tags/google/stable/2018-10-04)
```

It was updated immediately before the commit, 47a8729. The `clang-format`'s version installed by default via `brew install clang-format` in Travis CI has been updated recently and CI test comes to fail. I guess some default value of options have been changed or some new configuratin are added in new version `clang-format`. I'll read the release note of clang-format and try to detect the cause. It would be better to modify `.clang-format` than to update `clang-format` itself, if possible.

**Comment by ki-foobar** [comment]
I've found the cause: https://bugs.llvm.org/show_bug.cgi?id=38525 I have not read the patch against this bug, but the description of the bug report is very similar to this commit (47a8729).

**Comment by ki-foobar** [comment]
This bug report says "incorrectly adds extra continuation indent spaces with BreakBeforeBinaryOperators set to All", but if the option is set to `NonAssignment` like this project, the bug occurred. Setting `None` is different from the current value, `NonAssignment` and should make much diff, but old `clang-format and new one output the same result.
