### ISSUE TITLE
Enter and space for general shortcut key does not work correctly

### ISSUE THREAD

**Issue by ki-foobar** [ElonaFoobar/ElonaFoobar#1083]
# Environment

* OS version: Windows
* Elona foobar verision: v0.3.1

# Details

Even if you bind "Enter" action to `Keypad Enter` or `Space`, you cannot use these keys for general shortcut key, such as "search", "go down/up stairs", and "enter a local field map from a global map".

# How to reproduce

1. Bind "Enter" action to `Keypad Enter` and `Space`.
2. Try to do these actions.

**Comment by Ruin0x11** [comment]
The issue is `enter` used to have the desired behavior, but now it doesn't. `auto_action` is the action with the desired behavior, but `enter` isn't used in the main input query anymore, although it should. The solution would be to remove `auto_action` and just use `enter` instead.
