### ISSUE TITLE
You can't use "p" as selection key because it is used in character sheet menu

### ISSUE THREAD

**Issue by ki-foobar** [ElonaFoobar/ElonaFoobar#1099]
# Environment

* OS version: Windows
* Elona foobar verision: v0.3.1

# Details

`p` key is the 16th selection key in list menu, but you can't use the key in the latest version because `p` is also used in character sheet menu (to trigger change appearance men).

# Solution

Introduce another context, hard-code something in character sheet menu or something else?
Anyway the current keybinding system should be polished more not only for this issue but also for other bugs.

**Comment by Ruin0x11** [comment]
There are a lot more edge cases involving key names than I first thought. In this case it would likely be best to allow getting the key name as was done before, then checking for it in the character sheet menu, and also using the same key name method for other places where a key name is needed.

**Comment by ki-foobar** [comment]
fixed by #1102.
