### ISSUE TITLE
License & Credit texts extending outside

### ISSUE THREAD

**Issue by nanbansenji** [ElonaFoobar/ElonaFoobar#1204]
Hello, I am very glad to see the Elona's source code in GitHub. 
I really thank you for your insanely great work. 

# Environment
* OS version: macOS 10.14.2
* Elona Foobar version: latest develop 3dbe0e48c2df9398f635d9bbffe756d471c1b0b3

# Details
License & Credit texts extending outside (please see below).
![2019-02-28 2 18 19](https://user-images.githubusercontent.com/37776463/53513124-cb1d0f80-3b07-11e9-80d0-3e44c769f437.png)

# How to reproduce
1. select Japanese language at the first time boot.
2. select About > License (or Credit).

# Cause
it may be caused by the misjudgment of languages.

# Solution
My workaround 8b8d5d307ca0d5e38672f82de03a5f6805ea1f9d works for me.

# Related
#1122

**Comment by ki-foobar** [comment]
@nanbansenji 
Thank you for reporting. Could you send a pull request with that commit?
