### ISSUE TITLE
Prompt windows do not stop key repeating

### ISSUE THREAD

**Issue by ki-foobar** [ElonaFoobar/ElonaFoobar#1225]
# 環境 Environment

* OS version: macOS 10.14.3
* Elona foobar verision: develop

# 詳細 Details

Prompt windows like on Returning do not stop key repeating. It is very annoying to select maps I want to go.

# 再現方法 How to reproduce

~~1. Open spell window [v].
2. Select Return and press Enter.
3. The selection prompt is shown, and probably closed soon because the Enter key is still pressed and the prompt accepts repeating key input.~~

1. Open spell window [v].
2. Select Return via letter key, e.g., `b`.
3. The selection prompt is shown, and probably closed soon because the selection key is still pressed and the prompt accepts repeating key input.

**Comment by Ruin0x11** [comment]
Interestingly I can't reproduce this with my setup, even when holding Enter or another rebound key.

**Comment by ki-foobar** [comment]
The above "How to reproduce" section was wrong, Enter key does not cause the bug, and other letter selection keys, `a`, `b`, `c`, etc, do. For example, press `v` (open spell menu) and `b` (select return spell) can reproduce the bug at least for me.
