### ISSUE TITLE
Test case of `Item.count()` sometimes fail

### ISSUE THREAD

**Issue by ki-foobar** [ElonaFoobar/ElonaFoobar#1254]
# 環境 Environment

* OS version: macOS 10.14.3, Travis CI, Appveyor CI
* Elona foobar verision: develop

# 詳細 Details

```
2.608 s: Core API: FOV
TEST FILE: item.lua
	test Item.create	pass:  8   fail:  0    246ms
	test Item.has_enchantment	pass:  2   fail:  0    251ms
	test Item.count 	pass:  2   fail:  0    243ms
FAILURE: tests/lua/item.lua:59: (3 != 2)
FAILURE: tests/lua/item.lua:64: (4 != 3)
	test Item.iter  	pass:  0   fail:  2    262ms
SOME TESTS FAILED (12/14)
```

# 再現方法 How to reproduce

under investigation...

**Comment by Ruin0x11** [comment]
Might be due to the fact that maps with type `dungeon` will sometimes spawn a fountain with a 1/20th chance. I think I might have fixed this in some branch.

https://github.com/ElonaFoobar/ElonaFoobar/blob/1613bd012c3370d48c86dc76dc2b8854776515ce/src/elona/map.cpp#L59-L79

**Comment by ki-foobar** [comment]
[This commit](https://github.com/ElonaFoobar/ElonaFoobar/commit/08a29eef04d66763ccb46367312deaca3ee59b98) has fixed the bug. Closing.
