### ISSUE TITLE
Proposal: simplify mod configuration menu

### ISSUE THREAD

**Issue by ki-foobar** [ElonaFoobar/ElonaFoobar#1260]
# 詳細 Details

Configuration menu forms hierarchical structure.
Currently, mod configurations are located in the 4th level. ("menu A")

![image](https://user-images.githubusercontent.com/36858341/56792136-d52b6800-6843-11e9-958e-c3114830dc94.png)

The proposed structure ("menu B") is here:

![image](https://user-images.githubusercontent.com/36858341/56792526-c85b4400-6844-11e9-92a6-0b43b0996598.png)

-----------------------

Pros:
- Obviously, menu B is much simpler than menu A.
- You don't have to select submenu/press ENTER much.

Cons:
- We need to implement pagination of the configuration menu.
- If someone created a mod which have tens of options, the menu's UI/UX would be bad.

**Comment by Ruin0x11** [comment]
I agree that it will be necessary to paginate config options at some point. Personally I prefer the mod options to be in a submenu, if only for organization, but if it simplifies the code/access then it isn't necessary.

**Comment by ki-foobar** [comment]
@Ruin0x11 
I think most of the mods which have at least 1 option have a few options and do not need to structure them with submenu. The current well-structured config menu is consistent, but bothering for actual use, I think. However, it is obvious that the new menu I proposed become very hard to use  if the guess is wrong. Probably there is a better choice somewhere.

**Comment by ki-foobar** [comment]
Finally, I decide that I won't implement Menu B. See #1261 for a new simplified (a little bit) config menu.
