### ISSUE TITLE
Separate "core" mod into "base" and "elona122"

### ISSUE THREAD

**Issue by Ruin0x11** [elonafoobar/elonafoobar#1267]
# Details
The `core` mod is really composed of content of two kinds: content required for the game to run at all, and extra content specific to Elona 1.22, but not strictly required. To better support modding, `core` should be split into two parts.

- `base`: Content required for the game to run. Examples include systems like `chara_drop` currently in `exports/impl` and translations for fundamental systems like attacking and UI.
- `elona122`: Content added by Elona 1.22. It should include most if not all characters, items, etc.

The main benefit of doing this is to allow new mods to be created that don't depend on anything that `elona122` uses, but can instead be taken as dependencies by `elona122` itself. These mods can be standalone apart from `base`. Examples include generic mod frameworks like object properties, AI, the title system, a UI engine, network features, and so on.

To accomplish this:
1. Refactor locale keys to drop `locale` from `<mod>.locale`, then drop usage of `core.<key>` in internal code since it's so commonly used. Since the proposed change will affect a large portion of the naming of each locale key, it's best to get this refactoring out of the way first.
2. Out of any code fundamental to the game, rename its locale keys to `base`. The intention is that anything in `core` will be able to be moved to Lua entirely at some point (though not immediately necessary).
3. Remove `exports` and use the data or API creation systems instead.
4. Rename `core` to `elona122`.

The end result is that ElonaFoobar should be able to be run successfully after removing `elona122` from the `mod` directory. This probably entails creating some default data if `elona122` is missing. Fortunately this will be easy since the data system can be interfaced with Lua.

**Comment by ki-foobar** [comment]
We also have to newly add a lot of "null" data to fallback. For example, if no race is defined by mods, what race will the player character become? If there is no map, where will the PC sent first?

I think the name of "elona122" is verbose. Why not just "elona"? The two mods, base and elona122, will be referred very frequently, so shorter is better. "elona" is meaningful enough.

**Comment by Ruin0x11** [comment]
> For example, if no race is defined by mods, what race will the player character become? If there is no map, where will the PC sent first?

We init some fallbacks if nothing is already defined.

```lua
-- data.lua

if table.count(data["core.class"]) == 0 then
  table.insert(data["core.class"], { }) -- ...
end
```

The checking needs to be more robust, like to ensure at least one world map is defined, but that's the idea.

**Comment by ki-foobar** [comment]
Close this proposal. See https://github.com/elonafoobar/elonafoobar/pull/1537#issuecomment-596080262 for the reasons.
