### ISSUE TITLE
Change naming convention in Lua to camel case?

### ISSUE THREAD

**Issue by ki-foobar** [ElonaFoobar/ElonaFoobar#1318]
# 詳細 Details

I prefer `snake_case` to `camelCase` much, and apply it to both of C++ and Lua source I worte. However, names in `snake_case` are longer than `camelCase`, which should slow table lookup, string comparison and so on in Lua.

**Comment by Vorlent** [comment]
I think you should keep using snake_case. It will be very confusing if a function like "is_alive" is defined in C++ but it's used as "isAlive" in lua. Simply searching for the function name doesn't work.

**Comment by ki-foobar** [comment]
If we do that, we rename the corresponding function defined in `lua_env/lua_api/*.cpp` and `lua_env/lua_class/*.cpp`.

**Comment by ki-foobar** [comment]
Reject. It should be confusing that naming convention in Lua differs from that in C++.
