### ISSUE TITLE
In title menu, foobar crashes when you press selection key out of list

### ISSUE THREAD

**Issue by ki-foobar** [ElonaFoobar/ElonaFoobar#1367]
# 環境 Environment

* OS version: macOS 10.14.5
* Elona foobar verision: v0.4.3

# 詳細 Details

In title menu, foobar crashes when you press selection key out of list, e.g., <kbd>n</kbd>, <kbd>p</kbd>

**Comment by Vorlent** [comment]
I have created a PR that fixes this.
