### ISSUE TITLE
can not assign the asterisk to keybindings by JIS keyboard 

### ISSUE THREAD

**Issue by nanbansenji** [elonafoobar/elonafoobar#1433]
# 環境 Environment

* OS version: Windows10, macOS Mojave 10.14.6
* Elona foobar verision: v0.5.0
* JIS keyboard

# 詳細 Details
In the keybindings setting, " * " can not assign to  any commands.

my workaround 77cd8cf7130438e6091121b61ff92816d10ea9d2 seems to be able to assign the asterisk key in my environment, but I do not test on other Keyboard layouts.

# 再現方法 How to reproduce
ESC -> Game setting -> Keybindings -> select "Target" -> input asterisk("shift" +" : ") on keyboard -> update "primary" to empty

**Comment by ki-foobar** [comment]
cf. #982 

The current implementation assumes that all the players use US layout, although JIS layout is much more common in Japan. Idially, keybinding should work in not only US and JIS, but any layout. We have to delete manual handling of <kbd>Shift</kbd> first to do so.
