### ISSUE TITLE
Remove Android support?

### ISSUE THREAD

**Issue by ki-foobar** [elonafoobar/elonafoobar#1442]
This summer, Chinese game developer, Leiting Games, launched [Elona mobile](http://elona.leiting.com/) (iOS/Android). I have already played it tens of hours, and noticed that the user interface is highly optimized to mobile devices. Elona foobar supports Android and does work, but its UI is derived from desktop version, far away from mobile-friendly.

[TODO: screenshot here]

You can touch the top left panel and input arrow key, <kbd>Enter</kbd>, <kbd>g</kbd>, and <kbd>f</kbd>. The Chinese mobile Elona, in contrast, provides more and more rich UI, suitable for small display and touch input as if Elona were originally a mobile game!

As for Elona foobar, it must takes *a lot of time* to make the quality of the UI system close to the mobile Elona's. It is almost impossible, at least by myself. Elona on mobile is a very attractive idea, but it seems to cost too much to achieve.

**Comment by Tsunder** [comment]
I think while it is at a standstill for the moment, a solution may exist.

Another roguelike game, [Cataclysm:Dark Days Ahead](https://github.com/CleverRaven/Cataclysm-DDA/), has [a mobile (android) port](https://play.google.com/store/apps/details?id=com.cleverraven.cataclysmdda). Its control scheme while was not on par with dekstop, it was quite fluid and I found passable, even without an external keyboard!

It features touch controls (swiping/tapping) and notably a "recently pressed keys" row for special menus. 
![image](https://user-images.githubusercontent.com/5103517/66459241-aba57800-ea42-11e9-97d2-6e81877d4c7c.png)
 This allows the port to keep up to date with minimal changes to its control scheme, able to adapt to control changes fairly well.

That being said it is still a massive undertaking.

**Comment by Lazywater** [comment]
After playing  Elona mobile (leiting) for several days, i feel that game is like another variant of elona. Although it has some good idea like more character stories and good UI, some things related to gameplay are terrible, such as the item limit, numerical system planning, some locations are full of bugs. And it can't be a elona with variants from other people's idea. Anyway thanks for developing elona foobar, more grateful if there is any possibility for elona foobar android.
