### ISSUE TITLE
Multithread compilation

### ISSUE THREAD

**Issue by EvgenijM86** [elonafoobar/elonafoobar#1472]
Is it possible to compile this using more than one thread? I tried make build -j 8 and it does not work. This is more of a question than a feature request. And if this is not implemented I would like to know how difficult it will be to add. If it is not that difficult I might try to add it myself.

**Comment by EvgenijM86** [comment]
Ok, after a little bit of digging I have found a way to do this:

export CMAKE_BUILD_PARALLEL_LEVEL=8
make build

Now it shows 8 cc1plus threads running in a system monitor and it compiles the whole project in 3 minutes 16 seconds. You should probably update your README.md file to mention this.

**Comment by ki-foobar** [comment]
I use [ninja build](https://ninja-build.org/), a build system supporting parallel compilation by default. CMake can generate build rule for Ninja:

```sh
make CMAKE_ARGS="-GNinja" <BUILD TARGET>
```

Ninja is usually faster than `make`. I recommend that you use it if possible. I'll update `README.md` and mention the flag `CMAKE_BUILD_PARALLEL_LEVEL` and Ninja.
