### ISSUE TITLE
config.json is not correctly read

### ISSUE THREAD

**Issue by EvgenijM86** [elonafoobar/elonafoobar#1473]
In src/elona/config.cpp this line
```
    const auto obj =
        parse_json5_file(filesystem::files::profile_local_config());
```
reads config.json as "core->category->option", but it later is used as "category->option", without specifying "core":

```
    // screen.fullscreen (default: "windowed")
    g_config.set_fullscreen(convert_to_fullscreen(get_value_by_nesting_key(
        obj, {"screen", "fullscreen"}, json5::string_type{"windowed"})));
```
And this results in searching for "screen" key in array with only "core" key present and thus not finding the correct key and returning the default value.

One can fix this error by changing the first line to be something like this:
```
    const auto obj2 =
        parse_json5_file(filesystem::files::profile_local_config());
    const auto obj = obj2.at("core").get_object();
```

One more issue with config.json is that it is overwritten each time you do a "make build". It would be much more convenient if it only done that if that file is missing. And the default version that it copies is outdated and does not have newer options. And it seems that whatever option you set in the game menu is not saved to config.json.

**Comment by EvgenijM86** [comment]
It seems the bug with config not saving is related to options with std::string type. Like:
```
CONFIG_OPTION("anime.auto_turn_speed", std::string, auto_turn_speed);
CONFIG_OPTION("screen.display_mode", std::string, display_mode);
```

**Comment by ki-foobar** [comment]
Thank you for your bug report. I'm investigate it.
