### ISSUE TITLE
Improving Elona graphics without artists

### ISSUE THREAD

**Issue by EvgenijM86** [elonafoobar/elonafoobar#1475]
Just an idea. There are websites that use neural networks to generate anime faces that sometimes look much better than Elona default. Like:
https://make.girls.moe/

And there is a higher resolution tech called StyleGan:
https://artbreeder.com/  - requires registration, and you can use it for various other art instead of just anime faces. It is semi-free, with a paid subscription option to remove some limitations.
https://waifulabs.com/
https://www.thiswaifudoesnotexist.net/ - cannot control anything, but it does have good resolution. It even generates character backstory...
https://www.obormot.net/demos/these-waifus-do-not-exist - same, but with more waifus.

Because those works are generated based upon millions of other images by various artist you cannot assign any meaningful copyright to them. It is like going to an art museum and then a day later your brain is having a dream where it imagines new art that is influenced by what you saw in museum.

**Comment by ki-foobar** [comment]
Interesting idea, but it does not match foobar's development policy ([GitHub Wiki page: Development policy](https://github.com/elonafoobar/elonafoobar/wiki/Elona-foobar-development-policy)).

> ## Principle
> 1. Elona foobar must be an elona.
> 2. Elona foobar must not crash or freeze.
> 3. Elona foobar must be improved.

Principle 1 means that plain Elona foobar (i.e., foobar without mods) must behave as the original (vanilla) Elona does. Look & feel enhancement is attractive, but it should be a mod. Make all graphics replaceable is one of the goals of Elona foobar. You will able to achieve such things as mods.
