### ISSUE TITLE
Random teleport of NPCs in towns.

### ISSUE THREAD

**Issue by EvgenijM86** [elonafoobar/elonafoobar#1479]
I am not sure if this is a bug or a feature, but NPC in towns randomly receive cursed items the longer you play. After a while this results in a ridiculous state when a large part of the town population just randomly teleports all over the place. This is especially annoying when doing quest, because NPC are not at their usual location and you sometimes need to spend several minutes to find them before they teleport to another random location.

I am not against NPC being capable of having cursed items and randomly finding them - that makes things more interesting (especially if you are searching for cursed equipment with certain attributes, and you can trade for it during "I want it!" quests), but I think there should be a dialogue option to attempt uncurse their equipment if you have the scrolls of uncurse with you.

**Comment by ki-foobar** [comment]
> I think there should be a dialogue option to attempt uncurse their equipment if you have the scrolls of uncurse with you.

You can give a scroll of uncurse to the NPC who are cursed via <kbd>G</kbd>ive menu, or <kbd>Z</kbd>ap a rod of uncurse to the NPC.

**Comment by EvgenijM86** [comment]
I see, this is not an issue then.
