### ISSUE TITLE
Replacing magic numbers with enums.

### ISSUE THREAD

**Issue by EvgenijM86** [elonafoobar/elonafoobar#1488]
In a lot of cases it is hard to understand what exactly the code is doing because you have no clue what that magic number id refers to. Will you accept pull requests that replaces magic numbers with enums that has the same numerical value?

**Comment by ki-foobar** [comment]
Of course welcome.

These pull requests did that:

- #1438
- #852
- #678

The issue #850 might help you.

Such enums are defined in `src/elona/enums.hpp` as `enum class`, not just `enum`.

**Comment by EvgenijM86** [comment]
Thank for info.
