### ISSUE TITLE
sol.hpp causing compile errors

### ISSUE THREAD

**Issue by HawtMetal** [elonafoobar/elonafoobar#1622]
Hi,

I cant build using cmake cos sol.hpp keeps causing compiler errors. Is there some setting that i have to change? 

using cmake 3.11.1

**Comment by ki-foobar** [comment]
Could you paste the error message here? It will help us investigate the cause much.

Common error reasons:

1. Elona foobar requires the compiler which supports C++17. If you use system-provided compiler, it may be old for compiling the source. What is the compiler and its version you use? 

2. Some required dependencies may be missing. They are listed in "How To Build" section in README.md.

**Comment by HawtMetal** [comment]
Hi,

You were right, the compiler I was using did not support C++17, I updated it and managed to build the source but when I try to run elona_foobar.exe, i get errors of missing dlls

"The code execution cannot proceed because libssl-1_1-64.dll was not found" and
"The code execution cannot proceed because libcrypto-1_1-64.dll was not found"

Any idea what I should do?

Thanks a lot

**Comment by HawtMetal** [comment]
Hi, I managed to get the game running but it runs extremely slowly, do I need to adjust any settings?

Thanks

**Comment by ki-foobar** [comment]
> You were right, the compiler I was using did not support C++17, I updated it and managed to build the source but when I try to run elona_foobar.exe, i get errors of missing dlls
> 
> "The code execution cannot proceed because libssl-1_1-64.dll was not found" and
> "The code execution cannot proceed because libcrypto-1_1-64.dll was not found"
> 
> Any idea what I should do?

The easiest way is copying DLLs distributed with Elona foobar v0.7.1 ([download link](https://github.com/elonafoobar/elonafoobar/releases/v0.7.1)) to your build directory.

> Hi, I managed to get the game running but it runs extremely slowly, do I need to adjust any settings?
>
> Thanks

Generally speaking, the debug build that MSVC generates is badly slower than release build. You can generate a release build by running this command: `nmake build_release -f Makefile.win`.

**Comment by HawtMetal** [comment]
Alright, I will try that, thanks a lot for the help.
