### ISSUE TITLE
Can't input to console

### ISSUE THREAD

**Issue by 2254FB** [elonafoobar/elonafoobar#1625]
# 環境 Environment

* OS version:macOS 10.15.1
* Elona foobar version:0.7.1

# 詳細 Details

pressed F12,console showed up but I can't input anything to it.
For example,I pressed A and skill menu show up,nothing change on the console.
don't know is it a bug,or just I don't know the right way to input.
![Image](https://i.ibb.co/Xx39pfS/image.png)

# 再現方法 How to reproduce

**Comment by ki-foobar** [comment]
It is not a bug. <kbd>F12</kbd> is assigned to "Toggle Console", which shows or hides console window and *does not capture user input*. It is only for viewing the console output. To input console, type <kbd>Shift+F12</kbd>, bound to "Open Console" action, instead. I plan to remove the former in near release as it is confusing. It is recommended that you unbind <kbd>F12</kbd> and assign the key to "Open Console" action.

![image](https://user-images.githubusercontent.com/36858341/81505127-1942bb00-9328-11ea-99cb-a54cbf21a59c.png)

**Comment by 2254FB** [comment]
> It is not a bug. F12 is assigned to "Toggle Console", which shows or hides console window and _does not capture user input_. It is only for viewing the console output. To input console, type Shift+F12, bound to "Open Console" action, instead. I plan to remove the former in near release as it is confusing. It is recommended that you unbind F12 and assign the key to "Open Console" action.
> 
> ![image](https://user-images.githubusercontent.com/36858341/81505127-1942bb00-9328-11ea-99cb-a54cbf21a59c.png)

Oh,I see.Thank you and I'll close this issue.
