### ISSUE TITLE
Minimap icon for player becomes duplicated when entering maps

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#295]
# Environment

* OS version: Windows 7
* Elona Foobar verision: `develop`

# Details
The blue icon in the minimap indicating the player's position becomes duplicated when entering a new map from the world map.

# How to reproduce
1. Start a new character.
2. Exit Your Home.
3. Go to the Puppy Cave.

**Comment by ki-foobar** [comment]
Maybe it is an undocumented feature for debugging. These icons point to the position of upstairs/downstairs.
