### ISSUE TITLE
Out-of-bounds array access in init_fovlist

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#467]
# Environment

* OS version: Windows 7
* Elona Foobar verision: `develop`

# Details
There appears to be an out-of-bounds array access in `init_fovlist` inside `fov.cpp`. It may attempt to set `fovlist[17]`, but `fovlist` only has size `15`. This causes tests to fail on Windows because of a debug assertion. Linux and macOS report no failures.

**Comment by ki-foobar** [comment]
I'll fix it and re-run failed tests. Thank you.
