### ISSUE TITLE
Add system for addition and overriding of custom data

### ISSUE THREAD

**Issue by Ruin0x11** [elonafoobar/elonafoobar#523]
# Details
One of the most attractive features will be modding support. To that end, a system for adding and changing arbitrary data should be created. Data can take any shape, and should be stored somewhere for fast lookup. For example, one could create a new character definition.

```hcl
chara "my_chara" {
    name = "my_mod.locale.chara.my_chara" // localized string
    level = 40
    // ...
}
```

All data will use string IDs of the form `<mod name>.<namespace>.<more namespaces>`. The definition above will generate an ID based on the mod it originates from, since mods are given unique names. So for a mod named `my_mod`, the above would generate `my_mod.chara.my_chara`. 

In C++, this would be parsed into an HCL object and stored somewhere. Then, when the character's information is looked up:

```c++
auto definition_data = mod::s.get("my_mod.chara.my_chara");
std::cout << definition_data["name"] << " " << definition_data["level"] << std::endl;
```

This would replace some parts that would otherwise be baked into the C++ code and unavailable for tweaking.

Another feature the system should support is overriding of data. Players should be able to change the properties of any loaded definition like so:

```hcl
override chara "my_mod.chara.my_chara" {
    level = 9999
}
```

These would be resolved after all the base definitions are loaded.

The character loading is only an example; all sorts of data should be editable this way. With this system in place, it should be possible to add an editing system so people can edit things directly inside the game, and many more properties that are baked into the code can be externalized.

**Comment by ki-foobar** [comment]
Implemented.
