### ISSUE TITLE
Enter key has absurdly quick repeat rate

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#525]
# Environment

* OS version: Arch Linux 4.16.9-1-ARCH
* Elona Foobar verision: `develop`

# Details
The Enter/numpad enter keys have no keywait whatsoever, causing any pressing of them to repeat rapidly. But other keys seem to have normal keywait.

# How to reproduce
1. Start the game.
2. Press Enter.

**Comment by ki-foobar** [comment]
I found this issue just now too and is fixing now.
