### ISSUE TITLE
Add registering of custom functions to localization API

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#528]
# Details
For languages besides English and Japanese, more I18N functions might need to be added to suit the needs of translators. English already has functions like `he()` and `is()`, but they are currently baked into the C++ code. A system could be added which introduces a map of strings to localization functions implemented in Lua (`sol::function` function references), then functions could be registered using a Lua API.

```lua
local I18N = Elona.require("I18N")

function he(chara)
  if chara.sex == 0 then
    return "he"
  else if chara.sex == 1 then
    return "she"
  else
    return "it"
  end
end

I18N.register_function("he", he)
```

**Comment by ki-foobar** [comment]
It has already been implemented as `I18N` module.
