### ISSUE TITLE
Message box text cut off by 1 pixel/artifact at bottom

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#543]
# Details
The text box has some artifacts near the bottom, and text is cut off by 1 pixel.

![https://my.mixtape.moe/ryfcyz.png](https://my.mixtape.moe/ryfcyz.png)

**Comment by barff** [comment]
That looks very familiar. When playing Elona+ I changed the fontSize and msgLine options in config.txt. Distortions like what you have above occurred if i set things too high. Did you happen to tinker with those things?

**Comment by Ruin0x11** [comment]
I hadn't yet, but I think it's an issue that could be fixed. I wasn't aware that it still happened in Elona+, from what I remember.

**Comment by ki-foobar** [comment]
This issue is since vanilla, and no variants except oor solve it as far as I know.
I also think it is a bug to resolve, not by design.
