### ISSUE TITLE
Can't launch Foobar on Windows if path contains Japanese

### ISSUE THREAD

**Issue by ki-foobar** [ElonaFoobar/ElonaFoobar#550]
# Environment

* OS version: Windows
* Elona Foobar verision: v0.2.5

# How to reproduce

1. Rename the folder's name which contains executable to some Japanese word(or including non-ASCII characters).
2. Launch `ElonaFoobar.exe`.

# Cause

Maybe, Lua MOD engine cannot handle non-ascii filepath.

**Comment by Ruin0x11** [comment]
As far as I can understand, this isn't possible with stock Lua. `luaL_loadfile` takes a standard `char*` and has no awareness of `wchar_t`, so it simply cannot load filenames encoded with UTF-16. You'd have to apply a patch to get `wchar_t` support like https://bitbucket.org/doub/electronmeat/src/tip/srcweb/lua-5.1.4/lua-wstring.patch, but I would really like to avoid such a thing if possible.

**Comment by Ruin0x11** [comment]
[Here](https://stackoverflow.com/questions/24769623/opencv-imread-on-windows-for-non-ascii-file-names) is the same issue with `opencv`. Once again, the solutions were either to patch the code or use Windows APIs instead of `opencv` to open and read the file.

**Comment by ki-foobar** [comment]
I agree with limiting filename of user-created contents such as save folder names, mods and graphic/sound packs.
However, this problem occurs if a user names his account with non-ASCII characters and place Elona Foobar in his/her download folder, i.e., `C:\Users\{user name containing non-ascii}\Downloads`.
I don't want to make players rename the account, create a new account, or place another folder consisting of ASCII characters.
If there are no solution except for applying patch to Lua itself, we should do that because Elona has been played mainly in Japan, using non-ASCII characters mostly.

# Tasks

- Apply patch to Lua in order to accept UTF-16 filepath.
- Change naming convention of save file. Currently, `sav_{player name}`.
- Delete any filepath containing non-ASCII characters from save data completely. It means we must store all filepath as relative.
