### ISSUE TITLE
Add config system API

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#572]
# Details
Mods should be able to add their own config options for easy enabling/disabling of certain features.

This could be implemented in addition to a mod grouping system. Mods that contain much functionality could be grouped under one "omni mod" which depends on the individual mods providing certain features.

```hcl
mod "plusmod" {
    depends {
        plusmod_evolution = "0.1.0"
        plusmod_sprites = "0.1.0"
        # ...
    }
}
```

The individual mods could then expose config features.
```hcl
config "ElonaPlus (evolution)" {
    # ...
}
```

Then the omni mod could group certain configs together.
```hcl
config_group "ElonaPlus" {
    group = ["plusmod_evolution", "plusmod_sprites"]
}
```

**Comment by ki-foobar** [comment]
All(or almost all) options should be modified via GUI option menu by writing these lines:

```hcl
config "xxx" {
    name = "modname.xxx" // locale resource key
    type = "integer"
    min = 1
    max = 10
}
```

It makes this option configurable in option menu like built-in options.
