### ISSUE TITLE
When exiting blackjack, items on the ground get transparent

### ISSUE THREAD

**Issue by ki-foobar** [ElonaFoobar/ElonaFoobar#574]
# Environment

* OS version: Windows
* Elona Foobar verision: v0.2.5

# Details

When you select `Later` at casino and exit there, items on the ground get transparent.

# Cause

At [this line](https://github.com/ElonaFoobar/ElonaFoobar/blob/9eca33596d07dc7d034464124275ab738a5e65ab/item.cpp#L500), `cell_refresh` is called, and it delete the information about item(s) on the cell.

**Comment by ki-foobar** [comment]
Ah, I found out that the cause was simpler. Just lack of condition in `item_remove`.
i.e.,
```cpp
in item_remove()

...
if (on_ground && mode != 6 && mode != 9) // check also `mode`.
{
    cell_refresh(...);
}
...
```

**Comment by ki-foobar** [comment]
This bug seems to cause many issues, so it is better to delete `item_remove()`.

**Comment by ki-foobar** [comment]
I tried to find these change:

```cpp
// Before
inv[ci].number = 0;
cell_refresh(inv[ci].position.x, inv[ci].position.y);

// After
item_remove(inv[ci]);
```

However, no that change was done at #439.

Thus, we can replace safely code A with code B:

```cpp
// A (current)
void item_remove(item& i)
{
    i.number = 0;

    // It seems like item images are not removed from the map if the
    // item is on the ground, so explicitly clear them.
    bool on_ground = i.index >= 5080;
    if(on_ground)
    {
        cell_refresh(i.position.x, i.position.y);
    }
    lua::lua.on_item_removal(i);
}

// B
void item_remove(item& i)
{
    i.number = 0;
    lua::lua.on_item_removal(i);
}
```

**Comment by Ruin0x11** [comment]
Whoops, my bad. The reason for the extra `cell_refresh` was because when removing items with the `Item.remove` API function, the item icons would still remain on the tiles even though the item was removed. It seemed like this bug was displaying the exact opposite.
