### ISSUE TITLE
Refactor sprite drawing system to access images by string ID

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#603]
# Details
The current sprite drawing code relies on the `chipc/chipi` vectors to provide predefined offsets into sprite textures for rendering. Here are the parameters.

```
chipi/c(0) = spritesheet X
chipi/c(1) = spritesheet Y
chipi/c(2) = sprite width
chipi/c(3) = sprite height
chipi/c(4) = sprite draw Y offset
chipi(5) = height added in stack on ground
chipi(6) = shadow size
chipi(7) = animation delay (torches, etc.)
```

In the current system, sprites are referred to by an integer ID. In order to support extensibility, this system should be refactored so
1. Sprites can be referred to as strings (`core.image.xyz`)
2. The whole assortment of sprites isn't loaded into memory at once (For user-added sprites only. The base game's sprites could marked specially to always be loaded.)
3. Sprites can be distributed as individual images instead of packed together.

This might as well be generalized to other images beside sprites as well, like the interface. Here is a first-glance proposal.

1. Create a texture packing class that stores the sprite data. Initially load the base sprites (after their definitions/overrides are loaded from config files).
2. When a sprite is requested and not found in the texture cache, load it from disk, pack it into the cache and store extents to it (X, Y, width, height). The cache uses textures of a predefined size, and if an image can't be fit then a new texture is allocated.
3. When a sprite is queried and found in the cache, return its extents to be used with `prepare_item_image` or similar.
4. At certain intervals, evacuate the cache to prevent it from growing too large. (For user-added sprites only. The base game's sprites could marked specially to always be kept.)

Each category of texture should be kept separate, like sprites versus tiles.

For compatibility, a predefined set of sprite extents can be loaded at startup for the existing `.bmp` files so no editing has to be done to them.

To provide the same amount of data as the previous `chipi` vector has, sprites could be defined externally. The sprite size could be introspected from the image file passed in.

```hcl
image "pillar" { # produces core.image.pillar
   filename = "assets/pillar.png"
   stack_height = 24
   draw_offset_y = 12
   shadow_size = 24
}
```

Also, some accommodation for sprites with variations needs to be made, like for torches. In this case a single sprite ID could have multiple variants, each with their own extents. Then the variant can be selected by ID or defaulted to 0.

# Future Development
There would still be more work to be done at some later date for truly efficient rendering. This would have to be accomplished using shaders and OpenGL, and it would take a long time to refactor the imperative graphics code to use a render queue instead. It seems daunting, although most uses of `gcopy` and the like are usually one of 

- UI
- sprites
- animations

In the distant future a render-queue based system that uses textures bound to OpenGL could batch together draw operations of these kinds to take advantage of graphics hardware. This will probably be necessary to make the game playable at reasonable speeds on mobile platforms.

**Comment by ki-foobar** [comment]
# API Draft

```cpp
In C++
// Substitutes gcopy
renderer.draw("foo.bar.baz", x, y);
// Substitutes gzoom
renderer.draw("foo.bar.baz", x, y, width, height);
// Substitutes grotate
renderer.draw("foo.bar.baz", center_x, center_y, angle);
renderer.draw("foo.bar.baz", center_x, center_y, angle, width, height);
```

**Comment by barff** [comment]
https://developer.apple.com/macos/whats-new/
CTRL+f to Find ... Deprecation of OpenGL and OpenCL

How will this affect future plans/development on this front?

**Comment by Ruin0x11** [comment]
This is now handled by `pic_loader.cpp` for character and item sprites (save for caching). Refactoring the code internally to use the string ID instead of an integer will be a separate task.
