### ISSUE TITLE
Blackjack/casino auto-advances through menus

### ISSUE THREAD

**Issue by barff** [ElonaFoobar/ElonaFoobar#625]
# Environment

* OS version: w7
* Elona Foobar verision: 0.2.6

# Details
Blackjack does not allow choices, instead the game seems to press Enter immediately, thus shutting the player out. Mashing Down Arrow has a chance to disrupt this, allowing a player to choose a bet. However, this fails after cards are dealt. You will always choose Stay. Since the AI cheats I chose to grab Lucky Day to see how far I could go with this glitch. Quite amusing.

A terrible video of it in action
https://mega.nz/#!69JHnAJb!Lm6nC7esXXDdjgBYPuR0pp6cThIsxc5-2etaoOnyrRI

# How to reproduce
Enter blackjack/casino

**Comment by Ruin0x11** [comment]
Seems to be caused by the enter key not being delayed in all circumstances. I can fix this.
