### ISSUE TITLE
I18n error: "<Unknown ID: core.locale.death_by.other>"

### ISSUE THREAD

**Issue by ki-foobar** [ElonaFoobar/ElonaFoobar#632]
# Environment

* OS version: macOS
* Elona Foobar verision: develop

# Details
![image](https://user-images.githubusercontent.com/36858341/41928136-2f77ce90-79af-11e8-804e-a51478d12188.png)

# How to reproduce

Die by starving.

**Comment by Ruin0x11** [comment]
I think I fixed this in one of the many I18N PRs. I'll open a small PR for it.
