### ISSUE TITLE
Strange message in score menu when you die.

### ISSUE THREAD

**Issue by ki-foobar** [ElonaFoobar/ElonaFoobar#633]
# Environment

* OS version: macOS
* Elona Foobar verision: develop

# Details

![image](https://user-images.githubusercontent.com/36858341/41928390-f78457e6-79af-11e8-888a-e1013899063d.png)

The randomly selected words represents my thought well.
> What's happened?

# How to reproduce

Be killed by some character.

**Comment by Ruin0x11** [comment]
Seems to be caused by the wrong formatting target being used. It is currently:

```
ndeathcause = i18n::s.get(
   "core.locale.death_by.chara.killed.passive", cdata[prm_855]);
```

But `prm_855` is the attacker, so it should be `cc` instead.
