### ISSUE TITLE
Make item description easier to write

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#743]
# Details
When creating a new item, the `description_jp` fields contain internal formatting characters. These should be made into localized strings, and the same description format should be used across all languages.

Since there are now English translations of all the extended item descriptions in the recent Omake Overhaul English version, perhaps the author could be contacted about including them here.

```hcl
# before
description_jp_0 = "\t\t古代文字の書かれた石。使用すると、この世界ではないどこかの入り口が開くとされている。\n#〜あなたの見知らぬ世界〜\n"
description_jp_1 = ""
description_jp_2 = ""
description_jp_3 = "\t\t使用することでショウルームに行くことができる道具だ。\n#〜鑑定報告書：＜器具＞カテゴリ〜\n"

# after
description {
    main {
        text = "使用することでショウルームに行くことができる道具だ。"
        footnote = "〜鑑定報告書：＜器具＞カテゴリ〜"
    }
    extra_1 {
        text = "古代文字の書かれた石。使用すると、この世界ではないどこかの入り口が開くとされている。"
        footnote = "〜あなたの見知らぬ世界〜"
    }
}
```

**Comment by ki-foobar** [comment]
> Since there are now English translations of all the extended item descriptions in the recent Omake Overhaul English version, perhaps the author could be contacted about including them here.

I have a plan to contact Doorknob, the main translator and port English patch for omake and omake overhaul immediately after I complete the current task(#716). Fortunately, I have all of `diff` he and I applied to omake and oo's English version.
