### ISSUE TITLE
Automatic Lua API documentation generation

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#761]
# Details
Right now, splitting the API into C++ code and Lua documentation makes it annoying to update both at the same time. But LDoc doesn't parse C++ well, so the current system is used. Instead, create a system to automatically generate the `.luadoc` files using only Doxygen syntax in each C++ API source file. This way the documentation will be the same as the C++ code's and it will be located closest to the C++ interface so it can be updated more easily.

To help the parser, a special nonstandard Doxygen command like `\ldoc` could be used to denote a comment that should be generated as LDoc.

**Comment by ki-foobar** [comment]
It has already been implemented in `tools/docten` folder.
