### ISSUE TITLE
Navigation slowdown in Help menu

### ISSUE THREAD

**Issue by Morganeon** [ElonaFoobar/ElonaFoobar#792]
# Environment

* OS version: Windows 7.1
* Elona Foobar version: 0.2.6

# Details

Accessing the *Help* <?> page incur a major slowdown, and after reading one of the category the navigation is also slowed down.

# How to reproduce

Press <?>, scroll to any option, press enter, try to scroll to other option to see lag appearing.

# Cause

First slowdown is caused by the for loop at line 612 in menu.cpp (5.41s in debug build to get in and out).

The for loop goes through 818 items with a rate of 1 item per 8ms, resulting in a >5000 ms loop.

Navigation slowdown seems to be linked to the amount of rendered text (A good example being Adventurers in page 3 having a fast navigation, and Rank & Salary on the same page having a really slow navigation)

# Solution

None for now, will dig deeper into the two issues tomorrow, still familiarizing with the code, forked today.

**Comment by Ruin0x11** [comment]
Hi. Thanks for filing an issue. The state of the UI code is quite inefficient since for many menus the entire drawing logic is redone each frame. That and all the drawing code is procedural, so graphics hardware can't really be taken advantage of. But lots of things can be memoized, it's just that there's so much code to refactor that it's a bit overwhelming at first.

**Comment by Ruin0x11** [comment]
Currently the refactoring for menus/windows is similar to the following.

https://github.com/ElonaFoobar/ElonaFoobar/commit/1f1aa2fd8ff4d58ce64734f24858bad24c6690e6

Basically, the process is to move all per-frame drawing code into `draw()` of a `ui_menu` subclass, move expensive things to `update()`, and reupdate when input is received.

**Comment by Morganeon** [comment]
Starting a PR for this issue.

**Comment by Morganeon** [comment]
Dear Ruin0x11,

I've pulled the recent changes from /dev banch, and am getting the following errors on Window 7.1:

Error	C2923	'elona::optional': 'result_type' is not a valid template type argument for parameter 'T' (compiling source file ...\src\menu.cpp)	Elona_foobar	...\src\ui\ui_menu.hpp	51	
[...]
Error	C2923	'elona::optional': 'result_type' is not a valid template type argument for parameter 'T' (compiling source file ...\src\ui\ui_menu_npc_tone.cpp)	Elona_foobar	...\src\ui\ui_menu.hpp	51	


Error	C2253	'elona::ui::ui_menu<elona::ui::dummy_result>::on_key': pure specifier or abstract override specifier only allowed on virtual function (compiling source file ...\src\menu.cpp)	Elona_foobar	...\src\ui\ui_menu.hpp	51	
[...]
Error	C2253	'elona::ui::ui_menu<std::string>::on_key': pure specifier or abstract override specifier only allowed on virtual function (compiling source file ...\src\ui\ui_menu_npc_tone.cpp)	Elona_foobar	...\src\ui\ui_menu.hpp	51	


Error	C2065	'result_type': undeclared identifier (compiling source file ...\src\menu.cpp)	Elona_foobar	...\src\ui\ui_menu.hpp	51	
[...]
Error	C2065	'result_type': undeclared identifier (compiling source file ...\src\ui\ui_menu_npc_tone.cpp)	Elona_foobar	...\src\ui\ui_menu.hpp	51	


Error	C2061	syntax error: identifier 'result' (compiling source file ...\src\menu.cpp)	Elona_foobar	...\src\ui\ui_menu.hpp	45	
[...]
Error	C2061	syntax error: identifier 'result' (compiling source file ...\src\ui\ui_menu_npc_tone.cpp)	Elona_foobar	...\src\ui\ui_menu.hpp	59	


Error	C2062	type 'unknown-type' unexpected (compiling source file ...\src\menu.cpp)	Elona_foobar	...\src\ui\ui_menu.hpp	51	
[...]
Error	C2062	type 'unknown-type' unexpected (compiling source file ...\src\ui\ui_menu_npc_tone.cpp)	Elona_foobar	...\src\ui\ui_menu.hpp	51	


Error	C2238	unexpected token(s) preceding ';' (compiling source file ...\src\menu.cpp)	Elona_foobar	...\src\ui\ui_menu.hpp	45	
[...]
Error	C2238	unexpected token(s) preceding ';' (compiling source file ...\src\ui\ui_menu_npc_tone.cpp)	Elona_foobar	...\src\ui\ui_menu.hpp	51	

Error	C2334	unexpected token(s) preceding '{'; skipping apparent function body (compiling source file ...\src\menu.cpp)	Elona_foobar	...\src\ui\ui_menu.hpp	60
[...]
Error	C2334	unexpected token(s) preceding '{'; skipping apparent function body (compiling source file ...\src\ui\ui_menu_npc_tone.cpp)	Elona_foobar	...\src\ui\ui_menu.hpp	60	



[...] represent the same errors for all the /ui/ files.

Is the current state of the development branch not compiling or is it a problem on my end?

**Comment by Morganeon** [comment]
Looks like a linker error to me, I remember seeing a class to struct PR fix but I can't seem to find it anymore, could this be related?

**Comment by Ruin0x11** [comment]
There indeed was a linker error, which I thought I fixed since the latest Appveyor build passed. The type was `class` instead of `struct` for certain forward declarations.

https://github.com/Ruin0x11/ElonaFoobar/commit/2b10dfb45be2f03681711b16a0b24531a10eb01c

**Comment by Ruin0x11** [comment]
Should be merged by now, could you try once more?

**Comment by Morganeon** [comment]
Same errors at compile time. Both via MSVC and via nmake -f Makefile.win. 

Please find the error dump below,

Cheers, Morgan.

https://pastebin.com/UWGrgcEJ

**Comment by Morganeon** [comment]
The current development branch on my fork is the one with exact code. I can't PR it since it says that it is the same as the current development branch.

Please find below the archive of what is inside my ElonaFoobar/src repo. I hope it isn't a misconfiguration or an incompatibility on my end.

https://www.dropbox.com/s/6l1rrchyq5t6kpv/ElonaFoobar.rar?dl=0

**Comment by Ruin0x11** [comment]
Seems to compile okay on my end. Could you provide the versions of CMake, MSVC and Visual Studio you use? Here are mine for reference.

```
-- The C compiler identification is MSVC 19.13.26132.0
-- The CXX compiler identification is MSVC 19.13.26132.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works

>cmake --version
cmake version 3.11.1
```

**Comment by Morganeon** [comment]
`-- Selecting Windows SDK version 10.0.16299.0 to target Windows 6.1.7601.
-- The C compiler identification is MSVC 19.11.25508.2
-- The CXX compiler identification is MSVC 19.11.25508.2
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe -- works

>cmake --version
cmake version 3.12.1
`

I'll put everything up to date and get back in touch with you.

**Comment by Morganeon** [comment]
Build passed, the culprit was indeed Visual Studio being outdated. I'm now facing a new issue, a runtime error when selecting the language (https://my.mixtape.moe/vrigtj.png). I'll try and fix this when back from work.

Thanks for your patience and your help.

**Comment by Ruin0x11** [comment]
I think this is a result of the files in `bin/Debug/runtime` being outdated. The content for the file in question was changed in [this commit](https://github.com/ElonaFoobar/ElonaFoobar/commit/d879834d5bc113fca3ff7f57e0f64c05216bf12a#diff-bd865d66ccb6b28d5925858712ff114c). The files in `runtime` will only be updated if they are removed or the project is cleaned.

**Comment by Morganeon** [comment]
It was indeed a problem with outdated files. Everything is running fine now, thanks once again for your time and patience! Working on my first PR now. :+1:
