### ISSUE TITLE
Missing contributing.md and other files in version 0.2.6

### ISSUE THREAD

**Issue by Morganeon** [ElonaFoobar/ElonaFoobar#794]
# Details

The folder /Blob/, containing contributing.md and code_style.md, is missing in version 0.2.6. It can be found in version 0.2.5 at the following url: 
https://github.com/ElonaFoobar/ElonaFoobar/blob/v0.2.5/CONTRIBUTING.md
https://github.com/ElonaFoobar/ElonaFoobar/blob/v0.2.5/CODE_STYLE.md

Links in readme.md are therefore currently broken.

**Comment by Morganeon** [comment]
Those files can be found in .github in 0.2.6, just need to correct the links.

**Comment by Ruin0x11** [comment]
Closed by #795.
