### ISSUE TITLE
Rebuild should always overwrite files in `bin`

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#800]
# Details
During development, I end up changing many files in `runtime` frequently, like `runtime/data/script/*.lua` for testing. But the current build system will not overwrite files that already exist, so I have to copy them manually or edit them in `bin` before they get deleted later. It also causes issues like https://github.com/ElonaFoobar/ElonaFoobar/issues/792#issuecomment-413947549 and #689. I'm wondering if there's any need to not overwrite existing files. I use a shell script to manually copy all `runtime` files before running anything anyway, bypassing the build system copying mechanism entirely, and the operation itself finishes almost instantly.

**Comment by Morganeon** [comment]
The CI tests also currently re-download elona 1.22 from elona website (`wget --no-verbose "http://ylvania.style.coocan.jp/file/elona122.zip"`), which might be impractical if it moves / gets deleted / gets unavailable. Might want to mirror it somewhere related to the repo.

**Comment by Ruin0x11** [comment]
That would be convenient, but we would have to make sure to obtain permission to redistribute first. Most of the assets are not redistributable since they were made by various authors with unknown policy on redistribution.
