### ISSUE TITLE
Structurize `gdata`

### ISSUE THREAD

**Issue by ki-foobar** [ElonaFoobar/ElonaFoobar#851]
# Details

Currently, `gdata` is just an array and we access each member via macro. Define `struct GameData` instead.

# Tasks

- Delete direct access to `gdata` i.e., access without macro.
- Define `struct GameData` and replace existing `gdata`'s definition with the struct.
- Add migration for save data.

**Comment by ki-foobar** [comment]
Umm... there are more raw `gdata` access than I expected...

**Comment by ki-foobar** [comment]
```
skill rackers
  750 - 759 (10)
ranking
  120 - 128 (9) rank
  140 - 148 (9) deadline
shortcut
  40 - 59 (20)
disease history
  700 - 719 (20)
quests
  160 - 164 (5)
deck
  830 - 834 (5)
```

**Comment by ki-foobar** [comment]
```
gdata(9)
gdata(20)
gdata(30)
gdata(31)
gdata(32)
gdata(33)
gdata(34)
gdata(35)
gdata(41)
gdata(42)
gdata(43)
gdata(60)
gdata(61)
gdata(62)
gdata(71)
gdata(73)
gdata(74)
gdata(77)
gdata(78)
gdata(79)
gdata(86)
gdata(87)
gdata(89)
gdata(91)
gdata(94)
gdata(98)
gdata(120)
gdata(121)
gdata(123)
gdata(124)
gdata(125)
gdata(128)
gdata(171)
gdata(184)
gdata(186)
gdata(201)
gdata(202)
gdata(203)
gdata(204)
gdata(205)
gdata(206)
gdata(207)
gdata(208)
gdata(209)
gdata(210)
gdata(211)
gdata(212)
gdata(213)
gdata(214)
gdata(215)
gdata(216)
gdata(217)
gdata(802)
gdata(808)
gdata(809)
gdata(813)
gdata(815)
gdata(820)
gdata(827)
gdata(850)
```

**Comment by Ruin0x11** [comment]
We could create `GameData` and a temporary shim to assist with serialization by copying `GameData` fields into `gdata` then serializing normally, then reversing the process for deserialization. Then each field could be refactored one at a time.
