### ISSUE TITLE
I18N Errors or typos in v0.2.8 or later

### ISSUE THREAD

**Issue by ki-foobar** [elonafoobar/elonafoobar#937]
[FIXED]

# Environment

* OS version: macOS
* Elona foobar verision: develop

# Details

![image](https://user-images.githubusercontent.com/36858341/45884880-fb8dae80-bdef-11e8-90a8-540da112ea19.png)

> \<invalid type\>

> \<\<lua object\>\>

Expected:
> 少女のモナミックとの関係が\<嫌い\>になった…

# How to reproduce

1. Wish "ally" and select your pet.
2. Kill him or her.

**Comment by ki-foobar** [comment]
Untranslated: https://github.com/ElonaFoobar/ElonaFoobar/blob/develop/src/mapgen.cpp#L2203

> cf. In OOEN and OOENh, "field nearby town"

**Comment by ki-foobar** [comment]
https://github.com/ElonaFoobar/ElonaFoobar/blob/develop/runtime/locale/en/chara.hcl#L45

> Innkeeper => innkeeper (uppercase I to lowercase i)

**Comment by ki-foobar** [comment]
In https://github.com/ElonaFoobar/ElonaFoobar/blob/develop/runtime/mods/core/data/chara.lua and https://github.com/ElonaFoobar/ElonaFoobar/blob/develop/runtime/mods/core/data/chara_chip.lua

`イークの首領『ルードルボ』` does not have English name, and is just called `yeek`.
`ルードルボ` is reverse spelling of `ボルドール`(Boldor), a monster in Angband.

**Comment by ki-foobar** [comment]
![image](https://user-images.githubusercontent.com/36858341/47600099-ec091300-d9f6-11e8-9b42-04bbd0f526b8.png)

**Comment by ki-foobar** [comment]
In keybinding menu,
```
Menu category:
  特定 => 詳細
  identify => details/show details/see details/known info, I don't know which is the best, but anyway "x" key does not "identify" in this context(menu).

Game category:
取る => 拾う
混ざる => 混ぜる
あげる => 渡す
```

**Comment by ki-foobar** [comment]
![image](https://user-images.githubusercontent.com/36858341/47623050-d1967d00-db4f-11e8-9254-72cb594bf425.png)

**Comment by ki-foobar** [comment]
missing period:

> You hear something scratching for warms
> You hear poultry in the distance
> You hear someone adjusting their armor for the umpteenth time
> You hear someone humming the *Money* tune while cracking their knuckles
> You hear someone muttering sulfurously somewhere.

**Comment by ki-foobar** [comment]
![image](https://user-images.githubusercontent.com/36858341/47937018-dded5200-df22-11e8-9cc4-d49b3419cd25.png)

**Comment by ki-foobar** [comment]
diminishs -> diminishes

**Comment by ki-foobar** [comment]
> 何かを釣竿に装着した。

`何か` should be a concrete bait.

**Comment by ki-foobar** [comment]
When you eat an equipment that increases your stats, These message will be shown:

> Your will softens. Your will deteriorates.

I think reverse order is better.

**Comment by ki-foobar** [comment]
In English journal, some story item lack brackets(`[``]`).

**Comment by ki-foobar** [comment]
Some English font does not have ellipsis glyph, but it is used in Elona text in some places.

**Comment by ki-foobar** [comment]
The description of priest class has ",,".

**Comment by ki-foobar** [comment]
typo: teleporation -> teleportation

**Comment by ki-foobar** [comment]
>  A deep sense of peace fills your heart.

Delete the leading space.

**Comment by ki-foobar** [comment]
In Japanese item description menu, the last Japanese period 「。」should be removed, but does not now.

**Comment by ki-foobar** [comment]
If the option `screen.skip_random_event_popups` is on, the order of message gets wield.

**Comment by ki-foobar** [comment]
Lexus appears to be a bilingual.

![image](https://user-images.githubusercontent.com/36858341/49872483-8a90ec80-fe5c-11e8-99a4-b6b49e9ba333.png)

**Comment by Vorlent** [comment]
Elona 3.0 has been released. You can close this issue.

**Comment by ki-foobar** [comment]
Issues which are not marked as [DONE] have not been resolved yet.
