### ISSUE TITLE
When trading item stack, only trade the minimum stack amount needed

### ISSUE THREAD

**Issue by Ruin0x11** [elonafoobar/elonafoobar#948]
# Details
When trading a stack of items, the whole stack will always be traded even if the minimum value needed is attained by a smaller portion of the stack. Instead, trade only the part of the stack which adds up to the minimum appropriate value.

# Variants having this feature

`omake_overhaul`

**Comment by ki-foobar** [comment]
It is useful, but such extension is a mod's business in Elona foobar.
