### ISSUE TITLE
Android,  crash at start with 'no display modes available'.

### ISSUE THREAD

**Issue by freijie** [elonafoobar/elonafoobar#959]
# Environment

* OS version: Android 7.1.2
* Elona foobar verision: 0.2.8?
* Hardware: XIAOMI Redmi 5A

# Details
Crash upon launch, after extracting contents of elona1.22.zip

# How to reproduce
Launch.

# Cause
Crashlog:

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/riva/riva:7.1.2/N2G47H/V9.6.5.0.NCKMIFD:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 19414, tid: 19616, name: SDLThread  >>> xyz.ki.elonafoobar <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'terminating with uncaught exception of type elona::snail::detail::SDLError: No display modes available'
    x0   0000000000000000  x1   0000000000004ca0  x2   0000000000000006  x3   0000000000000008
    x4   ffffffffffffffff  x5   0000000000000000  x6   0000000000008080  x7   6075601f7264636e
    x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  0000000000000001
    x12  ffffffffffffffff  x13  0000000000000000  x14  0000000000000000  x15  0002266b226ccdd7
    x16  0000007f86282ec8  x17  0000007f86230550  x18  00000000ffffffff  x19  0000007f68c0a4f8
    x20  0000000000000006  x21  0000007f68c0a450  x22  0000000000000002  x23  00000000ffffffc8
    x24  0000007f68c021a0  x25  0000007f68c02070  x26  0000007f68c020b0  x27  8bd76e2b0fa6c23c
    x28  0000000000000003  x29  0000007f68c01f80  x30  0000007f8622d9e0
    sp   0000007f68c01f60  pc   0000007f86230558  pstate 0000000060000000

backtrace:
    #00 pc 000000000006b558  /system/lib64/libc.so (tgkill+8)
    #01 pc 00000000000689dc  /system/lib64/libc.so (pthread_kill+64)
    #02 pc 0000000000023f28  /system/lib64/libc.so (raise+24)
    #03 pc 000000000001c9ac  /system/lib64/libc.so (abort+52)
    #04 pc 00000000000a15ec  /data/app/xyz.ki.elonafoobar-1/lib/arm64/libc++_shared.so
    #05 pc 00000000000a17e8  /data/app/xyz.ki.elonafoobar-1/lib/arm64/libc++_shared.so
    #06 pc 00000000000c8108  /data/app/xyz.ki.elonafoobar-1/lib/arm64/libc++_shared.so
    #07 pc 00000000000c782c  /data/app/xyz.ki.elonafoobar-1/lib/arm64/libc++_shared.so
    #08 pc 00000000000c77ac  /data/app/xyz.ki.elonafoobar-1/lib/arm64/libc++_shared.so (__cxa_throw+120)
    #09 pc 000000000002b334  /data/app/xyz.ki.elonafoobar-1/lib/arm64/libsnail.so (_ZN5elona5snail11Application24get_default_display_modeEv+288)
    #10 pc 0000000000e7207c  /data/app/xyz.ki.elonafoobar-1/lib/arm64/libElona_foobar.so
    #11 pc 0000000000e67c04  /data/app/xyz.ki.elonafoobar-1/lib/arm64/libElona_foobar.so (_ZN5elona25initialize_config_preloadERKN5boost10filesystem4pathE+48)
    #12 pc 000000000087ff44  /data/app/xyz.ki.elonafoobar-1/lib/arm64/libElona_foobar.so (_ZN5elona3runEv+1344)
    #13 pc 000000000104d75c  /data/app/xyz.ki.elonafoobar-1/lib/arm64/libElona_foobar.so (SDL_main+132)
    #14 pc 0000000000040870  /data/app/xyz.ki.elonafoobar-1/lib/arm64/libSDL2.so (Java_org_libsdl_app_SDLActivity_nativeRunMain+660)
    #15 pc 000000000023c290  /data/app/xyz.ki.elonafoobar-1/oat/arm64/base.odex (offset 0x21e000)

**Comment by poland4000** [comment]
Incompatibility issue I believe. On my phone (also Android 7) with Android studio as the debugger it shown that java.nio.file is not accessible.  java.nio.file only exists in android 8 or above.

**Comment by ki-foobar** [comment]
Android support has been removed. See #1442 and #1476.
