### ISSUE TITLE
App death at launching on El Capitan

### ISSUE THREAD

**Issue by Tomon613** [ElonaFoobar/ElonaFoobar#98]
El capitan( MacBookPro Early 2015)上でコンパイルは通りましたが、アプリを起動しますと必ず落ち、ターミナルに下記のログが出力されます。どのように改善すればよいかご存知でしょうか？
また、ArchLinux上でもg++でコンパイルできましたが、同様のログを残して落ちます。

```
hoge:runtime hoge$ ./elonafoobar
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Abort trap: 6
hoge:runtime hoge$
```

拙いものですが英訳分も以下に載せておきます。

Application compiled with g++-HEAD always terminated abnormally, on El Capitan (MacbookProEarly2015) with the above log.

How can I fix it?

App compiled with g++ (boost installed, not g++-HEAD) on Arch Linux shows the same log,too.

**Comment by Hogetto** [comment]
QuickLoad&QuickSave機能の追加に伴い、新たにQL&QSのキー設定をconfig.jsonから読み込む様になったので
config.jsonの70行目辺りに
```
...
  "key_quick": "z",
  "key_quickinv": "x",
  "key_quickload": "F2",
  "key_quicksave": "F1",
  "key_read": "r",
  "key_rest": "R",
...
```
のようにkey_quickloadとkey_quicksaveを追加すると良いかもしれません。

**Comment by ElonaFoobar** [comment]
@Tomon613 
Thanks for reporting.
I cannot detect the cause of this issue due to Foobar's poor error log.
I' ll improve this unkind and meaningless log.

**Comment by ElonaFoobar** [comment]
@Hogetto 
Sorry, currently `README.md` and `CHANGELOG.md` do not work at all...
I'll update them as soon as possible.

**Comment by Tomon613** [comment]
@Hogetto 
ご助言ありがとうございます！おかげさまでEl Capitanで起動いたしました！(Archは別のエラーが出たので別途issueをたてたいと思います。)
ところで、起動の際に./graphic/interface_ex3.pngが要求されましたが、これは本家elonaのどのファイルを指すのでしょうか？
interface_ex.pngおよびinterface_ex2.pngは本家のinterface.bmpとinterface2.bmpであると当たりをつけてしましたが...
今回の起動の際は本家のinterface.bmpをinterface_ex3.pngとして使いました。


With your advice, additing quick load & quick save settings to config.json, app was launched on El Capitan. Thank you! (But another error happened on Arch Linux, I will ask this on another issue.)
By the way, what are “interface_ex.png”, “interface_ex2.png” and “interface_ex3.png”? In my launching, I converted (or rename) “interface.bmp” and “interface2.bmp”, original elona graphic files, to “interface_ex.png” and “interface_ex2.png”. And “interface.bmp” was also converted to “interface_ex3.png”.

**Comment by ElonaFoobar** [comment]
These 3 files(`graphic/interface_ex{1,2,3}.png`) are transformed from `graphic/interface2.bmp` in vanilla.
See this pull request #26 for details.

Or comment out several lines like this:
```cpp
/* std.cpp, in picload() */
#if 0
     if (filename.generic_string().find(u8"interface.bmp") != std::string::npos)
     {
        ...
     }
#endif
```

**Comment by Tomon613** [comment]
@ElonaFoobar 
I see, thanks!
