### ISSUE TITLE
macOS Mojave: black screen

### ISSUE THREAD

**Issue by ki-foobar** [ElonaFoobar/ElonaFoobar#980]
# Environment

* OS version: macOS Mojave 10.14
* Elona foobar verision: develop

It occurs in both light and dark mode.

# Details

I tried to update Mojave and test Elona foobar, but entire screen was filled with black. Searching "SDL Mojave", I found some bug reports have already been posted.

Anyway, now, 26 October, we cannot play Elona foobar in macOS Mojave.

EDIT: Move, resize, or minimize window once. Then, everything work as usual.

**Comment by Ruin0x11** [comment]
Relevant SDL issue: https://bugzilla.libsdl.org/show_bug.cgi?id=4272

We should update to whichever version of SDL2 contains the patch included.

**Comment by ki-foobar** [comment]
already fixed
