### ISSUE TITLE
Many unknown_pragma warnings output under GCC

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#996]
# Environment

* OS version: Linux
* Elona foobar verision: `develop`

# Details
When compiling under GCC, there are many warnings of the following type.

```
/home/ruin/build/elonafoobar/src/ui/../data/types/../../lua_env/../shared_id.hpp:7: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push
```

# Solution
Add `-Wunknown-pragmas` to the list of ignored warnings.

**Comment by ki-foobar** [comment]
According to [clang official documentation](https://clang.llvm.org/docs/UsersManual.html#controlling-diagnostics-via-pragmas), the compiler accepts GCC style pragmas.


> The pragma may control any warning that can be used from the command line. Warnings may be set to ignored, warning, error, or fatal. The following example code will tell Clang or GCC to ignore the -Wall warnings:
> ```
> #pragma GCC diagnostic ignored "-Wall"
> ```
>
> In addition to all of the functionality provided by GCC’s pragma, Clang also allows you to push and pop the current warning state.
